create database bank;
show databases;
use bank;
drop database bank;
create table customer(cust_id varchar(10) primary key,c_name varchar(15) NOT NULL,city varchar(10));
create table Branch(Branch_id varchar(5) primary key,bname varchar(15),city varchar(10));
create table Deposit(Acc_no varchar(10) primary key,cust_id varchar(10) NOT NULL,Amount int,Branch_id varchar(5),Open_date date);
create table Borrow(Loan_no varchar(5) primary key,cust_id varchar(10),Branch_id varchar(5),Amount int);
desc customer;
desc Branch;
desc Deposit;
desc Borrow;
alter table customer add (address varchar(10));
alter table customer modify (c_name varchar(20));
alter table customer rename column address to new_address;
alter table customer drop column new_address;
rename table Branch to Branch1;
grant all on customer to user2;
revoke all on customer from user2;
truncate table customer;
drop table customer;
