select E.Emp_id,E.lname,E.fname,L.Loan_amt from Employee E inner join Loan L on E.Emp_id=L.Emp_id;
select E.Emp_id,E.lname,E.fname,L.Loan_amt from Employee E left join Loan L on E.Emp_id=L.Emp_id;
select E.Emp_id,E.lname,E.fname,L.Loan_amt from Employee E right join Loan L on E.Emp_id=L.Emp_id;
select E.Emp_id,E.lname,E.fname,L.Loan_amt from Employee E full outer join Loan L on E.Emp_id=L.Emp_id;
select Emp_id,fname from Employee union select Emp_id,fname from Loan;
select Emp_id,fname from Employee union all select Emp_id,fname from Loan;
select Emp_id,fname from Employee intersect select Emp_id,fname from Loan;
select Emp_id,fname from Employee except select Emp_id,fname from Loan;
select  count(*) from Employee E join Department D on E.Dep_id=D.Dep_id where D.name='Sales';
select Emp_id,lname,fname from Employee where Dep_id not in (10,30);
select Emp_id,lname,salary from Employee order by salary desc;
select Dep_id,count(*) from Employee group by Dep_id;
 select * from Employee where salary=(select max(salary) from Employee);
update Employee set salary=salary*1.10 where Job_id=(select Job_id from Job where func='Clerk');
select D.Dep_id,D.name from Department D left join Employee E on D.Dep_id=E.Dep_id where E.Emp_id is NULL;
select Dep_id,max(salary) as max_salary,min(salary) as min_salary,avg(salary) as avg_salary from Employee group by Dep_id;
select * from Employee where year(hiredate)=1985;
select E.* from Employee E join Department D on E.Dep_id=D.Dep_id join Location L on D.Location_id=L.Location_id where L.Reg_grp='New York';
select E.Emp_id,E.lname,E.fname,D.name from Employee E join Department D on E.Dep_id=D.Dep_id;
